name: content_based_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.0
  - pandas=2.2.2
  - scikit-learn=1.5.0  # Updated to compatible version
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - pip:
      - setuptools
      - wheel
      - mlflow==2.19.0
      - joblib==1.3.2
      - python-dotenv==1.0.0
