# MLproject/conda.yaml
name: content_based_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # <--- GANTI BARIS INI dari 3.12 ke 3.10
  - pip
  - numpy=2.0.2 # Verifikasi kompatibilitas dengan python 3.10
  - pandas=2.2.2 # Verifikasi kompatibilitas dengan python 3.10
  - scikit-learn=1.6.1 # Verifikasi kompatibilitas dengan python 3.10
  - cloudpickle=3.1.1 # Verifikasi kompatibilitas dengan python 3.10
  - psutil=7.0.0 # Verifikasi kompatibilitas dengan python 3.10
  - scipy=1.15.3 # Verifikasi kompatibilitas dengan python 3.10
  - pip:
      - setuptools
      - wheel
      - mlflow==3.1.0
      - joblib==1.3.2
      - python-dotenv==1.0.0
