name: content_based_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - setuptools
      - wheel
      - pandas==2.2.2
      - scikit-learn==1.6.1
      - numpy==1.24.0
      - mlflow==2.19.0
      - dagshub
      - joblib==1.3.2
      - matplotlib==3.8.0
      - seaborn==0.13.0
      - python-dotenv==1.0.0
