name: content_based_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12 # Diperbarui agar konsisten dengan lingkungan model yang dicatat MLflow.
  - pip
  - numpy=2.0.2 # Diperbarui agar sesuai dengan `requirements.txt` yang dicatat.
  - pandas=2.2.2 # Diperbarui agar sesuai dengan `requirements.txt` yang dicatat.
  - scikit-learn=1.6.1 # Diperbarui agar sesuai dengan `requirements.txt` yang dicatat.
  - cloudpickle=3.1.1 # Ditambahkan agar sesuai dengan `requirements.txt` yang dicatat.
  - psutil=7.0.0 # Ditambahkan agar sesuai dengan `requirements.txt` yang dicatat.
  - scipy=1.15.3 # Ditambahkan agar sesuai dengan `requirements.txt` yang dicatat.
  - pip:
      - setuptools
      - wheel
      - mlflow==3.1.0 # Diperbarui agar sesuai dengan `requirements.txt` yang dicatat.
      - joblib==1.3.2
      - python-dotenv==1.0.0
      # matplotlib dan seaborn dihapus jika tidak secara langsung dibutuhkan untuk inferensi model
      # Jika dibutuhkan untuk pengembangan umum, Anda bisa menambahkannya kembali.
