name: content_based_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=2.0.2
  - pandas=2.2.2
  - scikit-learn=1.6.1
  - cloudpickle=3.1.1
  - psutil=7.0.0
  - scipy=1.15.3
  - pip:
      - setuptools
      - wheel
      - mlflow==3.1.0
      - joblib==1.3.2
      - python-dotenv==1.0.0
