name: MLflow Project CI & Docker

on:
  push:
    paths:
      - 'MLproject/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mariouskono/workflow-ci
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # <--- GANTI BARIS INI dari 3.12 ke 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pastikan pyarrow diinstal sebagai biner (ini sudah benar dari perbaikan sebelumnya)
          pip install --only-binary=:all: pyarrow

          # Instal MLflow versi 3.1.0 (sesuai keinginan Anda)
          pip install "mlflow==3.1.0"

          # Dependensi lainnya (verifikasi kompatibilitas dengan Python 3.10)
          pip install "cloudpickle==3.1.1"
          pip install "numpy==2.0.2"
          pip install "pandas==2.2.2"
          pip install "psutil==7.0.0"
          pip install "scikit-learn==1.6.1"
          pip install "scipy==1.15.3"
          pip install "joblib==1.3.2"
          pip install "python-dotenv==1.0.0"
          pip install dagshub
          pip install matplotlib
          pip install seaborn

      - name: Verify installation
        run: |
          python -c "import numpy, pandas, sklearn, matplotlib, seaborn, mlflow, joblib; print('✅ All packages imported successfully')"

      - name: Force MLflow to use local tracking in CI
        run: |
          # Dapatkan jalur absolut ke direktori kerja runner
          WORKSPACE_DIR=$(pwd)
          # Atur MLFLOW_TRACKING_URI ke jalur lokal yang eksplisit dan absolut
          echo "MLFLOW_TRACKING_URI=file://$WORKSPACE_DIR/MLproject/mlruns" >> $GITHUB_ENV
          # Atur MLFLOW_ARTIFACT_URI secara eksplisit juga, untuk mengatasi masalah '/C:'
          echo "MLFLOW_ARTIFACT_URI=file://$WORKSPACE_DIR/MLproject/mlruns" >> $GITHUB_ENV
          echo "MLFLOW_DEBUG=true" >> $GITHUB_ENV # <--- TAMBAHKAN BARIS INI untuk debug yang lebih rinci

      - name: Run MLflow Project and Get Run ID
        id: mlflow_run_step
        run: |
          set -x # Mengaktifkan mode debug shell
          cd MLproject

          echo "### Debugging MLproject Directory and Script Execution ###"
          echo "--- Listing contents of MLproject/ with file types ---"
          ls -al .
          echo "--- Content of MLproject file (raw) ---"
          cat MLproject || echo "MLproject file not found or cannot be read."
          echo "--- Attempting to run modelling.py directly ---"
          set +e
          # modelling.py akan menggunakan MLFLOW_TRACKING_URI dan MLFLOW_ARTIFACT_URI yang diatur di atas
          python modelling.py --data_path dataset_tempat_wisata_bali_processed.csv
          PYTHON_DIRECT_RUN_EXIT_CODE=$?
          set -e
          echo "modelling.py direct run exit code: $PYTHON_DIRECT_RUN_EXIT_CODE"

          echo "--- Attempting MLflow Run with verbose output ---"
          # MLFLOW_VERBOSE=1 sudah disetel secara otomatis oleh MLFLOW_DEBUG=true
          MLFLOW_RUN_OUTPUT=$(mlflow run . --env-manager=local 2>&1)
          echo "$MLFLOW_RUN_OUTPUT"

          RUN_ID=$(echo "$MLFLOW_RUN_OUTPUT" | grep "=== Run (ID" | awk -F"'" '{print $2}')
          echo "mlflow_run_id=$RUN_ID" >> $GITHUB_OUTPUT
        continue-on-error: true # Tetap aktifkan ini untuk melihat semua output debug
        
      - name: Build Docker Image from MLflow Model
        run: |
          cd MLproject
          mlflow models build-docker -m "mlruns/0/${{ steps.mlflow_run_step.outputs.mlflow_run_id }}/artifacts/tfidf_model" -n ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: MLproject/**/*.joblib
