name: MLflow Project CI & Docker

on:
  push:
    paths:
      - 'MLproject/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mariouskono/workflow-ci
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mlflow==3.1.0"
          pip install "cloudpickle==3.1.1"
          pip install "numpy==2.0.2"
          pip install "pandas==2.2.2"
          pip install "psutil==7.0.0"
          pip install "scikit-learn==1.6.1"
          pip install "scipy==1.15.3"
          pip install "joblib==1.3.2"
          pip install "python-dotenv==1.0.0"
          pip install dagshub
          pip install matplotlib
          pip install seaborn

      - name: Verify installation
        run: |
          python -c "import numpy, pandas, sklearn, matplotlib, seaborn, mlflow, joblib; print('✅ All packages imported successfully')"

      - name: Run MLflow Project
        run: |
          cd MLproject
          mlflow run . --env-manager=local
        # Tambahkan langkah debug ini untuk memeriksa isi direktori MLproject
      - name: Debug - List MLproject directory contents
        run: |
          ls -l MLproject/ # Menampilkan daftar file di direktori MLproject

      - name: Read Run ID
        id: read_run_id
        run: |
          cd MLproject
          RUN_ID=$(cat mlflow_run_id.txt)
          echo "run_id_output=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build Docker Image from MLflow Model
        run: |
          cd MLproject
          mlflow models build-docker -m "mlruns/0/${{ steps.read_run_id.outputs.run_id_output }}/artifacts/tfidf_model" -n ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: MLproject/**/*.joblib
