name: MLflow Project CI & Docker

on:
  push:
    paths:
      - 'MLproject/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mariouskono/workflow-ci
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "numpy>=1.25.0,<2.0.0"
          pip install "pandas>=2.2.0,<2.3.0"
          pip install "scikit-learn>=1.5.0,<1.6.0"
          pip install "matplotlib>=3.8.0,<3.9.0"
          pip install "seaborn>=0.13.0,<0.14.0"
          pip install "mlflow>=2.19.0,<3.0.0"
          pip install "joblib>=1.3.0,<2.0.0"
          pip install "python-dotenv>=1.0.0,<2.0.0"
          pip install dagshub

      - name: Verify installation
        run: |
          python -c "import numpy, pandas, sklearn, matplotlib, seaborn, mlflow, joblib; print('✅ All packages imported successfully')"

      - name: Run MLflow Project
        run: |
          cd MLproject
          mlflow run . --env-manager=local

      - name: Read Run ID
        id: read_run_id
        run: |
          cd MLproject
          echo "RUN_ID=$(cat mlflow_run_id.txt)" >> $GITHUB_ENV

      - name: Build Docker Image from MLflow Model
        run: |
          cd MLproject
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/tfidf_model" -n ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: MLproject/**/*.joblib
